CREATE SCHEMA IF NOT EXISTS TELEMETRY;

DROP TABLE IF EXISTS TELEMETRY.DEVICE_STATUS_CURRENT;

CREATE TABLE TELEMETRY.DEVICE_STATUS_CURRENT (
    DEVICE_ID   VARCHAR(128) PRIMARY KEY,
    CPU_PCT     DECIMAL(5,2),
    MEM_PCT     DECIMAL(5,2),
    DISK_ALERT  CHAR(1),
    UPDATED_AT  TIMESTAMP
);
