CREATE TABLE telemetry_event (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id    VARCHAR2(64) NOT NULL,
  payload      CLOB NOT NULL,
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_telemetry_event_device_created
  ON telemetry_event(device_id, created_at);

